# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(886, 532)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 130, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(310, 90, 551, 421))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.check_kurer = QtWidgets.QComboBox(Form)
        self.check_kurer.setGeometry(QtCore.QRect(30, 170, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.check_kurer.setFont(font)
        self.check_kurer.setObjectName("check_kurer")
        self.btn_report = QtWidgets.QPushButton(Form)
        self.btn_report.setGeometry(QtCore.QRect(30, 260, 221, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_report.setFont(font)
        self.btn_report.setObjectName("btn_report")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(310, 50, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(440, 20, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lbl_count_orders = QtWidgets.QLabel(Form)
        self.lbl_count_orders.setGeometry(QtCore.QRect(790, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_count_orders.setFont(font)
        self.lbl_count_orders.setText("")
        self.lbl_count_orders.setObjectName("lbl_count_orders")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Админ"))
        self.label_4.setText(_translate("Form", "Выберите курьера"))
        self.btn_report.setText(_translate("Form", "Сформировать\n"
"отчёт"))
        self.label_5.setText(_translate("Form", "Отчёт"))
        self.label_6.setText(_translate("Form", "Кол-во сделанных заказов"))
