# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(539, 363)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(110, 40, 331, 91))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.le_password = QtWidgets.QLineEdit(Form)
        self.le_password.setGeometry(QtCore.QRect(110, 150, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.le_password.setFont(font)
        self.le_password.setObjectName("le_password")
        self.btn = QtWidgets.QPushButton(Form)
        self.btn.setGeometry(QtCore.QRect(180, 230, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.btn.setFont(font)
        self.btn.setObjectName("btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Введите пороль"))
        self.btn.setText(_translate("Form", "Войти"))
